### ISSUE TITLE
Vertical and HorizontalLayout are missing spacing & padding API

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-ordered-layout-flow#1]
@tmattsso commented on [Wed Sep 20 2017](https://github.com/vaadin/flow/issues/2448)

The margin API is quite convenient in many cases where the developer just wants a margin and nothing else; having a stylesheet is usually overkill.

---

@pleku commented on [Sat Sep 23 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331630229)

@jouni should this be somehow in Valo2 for `vaadin-vertical-layout` and `vaadin-horizontal-layout` or ? I don't see us just building an API for this on the server side that would be something that the user cannot tweak from their App Theme.

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331811053)

We have talked about this with the UX team. Not sure how, but I think we need to provide this, still. It would be great to have something like `setMargin(Margin.MEDIUM)`, where `Margin` is an enum of possible values. Same for spacing.

So, I’m expecting these to appear in the web component first, then we can create the corresponding server API.

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331811126)

I’ll open a new issue in the web component layout repo.

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331812619)

https://github.com/vaadin/vaadin-ordered-layout/issues/3

---

@Legioth commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331858271)

The same also applies for spacing. Should there be a separate ticket about that in this repository, or can we do both with this single ticket?

**Comment by jouni** [comment]
This issue is about margins specifically. My current view is that we might not add margins to layouts, only spacing, so it might make sense to separate these issues (like Leif suggested).

The current FW layout margin concept would rather be a “padding” concept in container elements, for things like windows/dialogs and cards/panels.

I would really like to get concrete examples where the Java developer needs to use the margins and a stylesheet is overkill. @tmattsso, do you any specific use case in mind?

**Comment by pleku** [comment]
@jouni just look at the most of the demos from http://flow.app.fi, those are really fugly since there is no margins set by the lazy developers, instead the text can start from the top-left 0, 0 ...

**Comment by jouni** [comment]
@pleku, sure I’m not questioning the need for making it easy to add white space in general. I’m just questioning if it’s a feature in this particular layout.

Also, we can blame Flow for overriding the default `body` margin. Without that, there would be at least some margin to make it easier to read the text. So maybe Flow should provide a way to control the viewport padding instead?

**Comment by Legioth** [comment]
Related to the discussion about the viewport padding: https://github.com/vaadin/flow/issues/2344

On the other hand, the issue with "margin" is not only in the upper left corner of the screen, but also inside any frame in the application.

**Comment by jouni** [comment]
> On the other hand, the issue with "margin" is not only in the upper left corner of the screen, but also inside any frame in the application.

Of course, and I was thinking if we could offer a ”padding” API for those ”frames” or “containers” instead. But this is hypothetical until we gather some concrete use cases and see which API makes more sense. I’ll try to get to that sooner than later.

**Comment by tmattsso** [comment]
Theres a lot of examples e.g. here: https://vaadin.com/success-stories

**Comment by jouni** [comment]
@tmattsso, the majority of those apps have been built by a team that had a designer to design the layouts and the theme, and most probably a team member who was comfortable in writing CSS.

I’m looking for examples where the UI is designed and written mainly by a Java developer, and where it would be expected and desired to have a great result nonetheless.

**Comment by tmattsso** [comment]
Margins might be tweaked with css later, this is true, but most margins inside the application are done by java devs calling setMargin. It is good enough during development and has a massive visual difference when demoing the un-themed app to stakeholders (spacing and icons are two other similarly important ones). It takes much, much longer for a java dev to create a 'good enough' look with CSS than calling an API method. While we like to believe that theming is a process that goes hand-in-hand with development, it isn't for most projects, including ours. My opinion is that we loose a lot of developer productivity if we remove these features.

**Comment by jouni** [comment]
> Margins might be tweaked with css later, this is true, but most margins inside the application are done by java devs calling setMargin

This is a good point and one that was also thinking, that how does the process usually go, even for a more designer-type of a developer: do they also prefer to build up a crude version with Java-only initially, and then tweak with CSS? But this doesn’t yet give an answer where the “white space API” should manifest itself.

> It takes much, much longer for a java dev to create a 'good enough' look with CSS than calling an API method.

Comparing `layout.setMargin(true)` vs `layout.getElement().getStyle().setProperty("padding", "20px")`?  Yes, it’s verbose and ugly, and probably enough to justify a convenience API (if we keep margins for layouts).

> My opinion is that we lose a lot of developer productivity if we remove these features.

I’m only questioning the `setMargin` API. Spacing (and icons, as you brought those up) are here to stay IMO as well. The specific API for spacing is still a bit unclear, and will be formulated in https://github.com/vaadin/vaadin-ordered-layout/issues/3

And like I hinted at earlier, I also believe we need a more convenience API for controlling the white space, on top of layout spacing. And perhaps the best way is still adding a margin/padding concept for layouts, but I’m just pressing on the subject so that we understand the reasons and needs for adding that API, and don’t add it just because we’ve “always” had it.

**Comment by tmattsso** [comment]
Questioning is fine; but what if we just re-create the V8 API for now (if it's a convenience method, thats fine, as long as it works), and think about more complex cases for V11? We know the current stuff works, and our devs are familiar with it. No need to fix everything, especially when adding this stuff is exactly the reason for faster major releases.

**Comment by jouni** [comment]
Yeah, I like the sound of that. I don’t want to delay this effort too much. There are some easier, small improvements we could still consider, which I’ve been discussing with our UX designers.

**Comment by jouni** [comment]
Just drafting, but here’s one idea:

**Set a certain size spacing *around and in between children***:
`setSpacing(Space.XS/S/M/L/XL/NONE)`

**Set a certain size spacing for a specific position of the layout**:
`setSpacing(Space.M, Position.TOP/RIGHT/BOTTOM/LEFT/INSIDE/ALL)`
- Not sure if “position” is the best word

**Allow specifying the same spacing value for multiple positions at once**:
`layout.setSpacing(Space.S, Position.TOP, Position.BOTTOM)`

This would unify the previous ”margin” and “spacing” concepts to one “white space” concept. A bit hesitant about naming it exactly the same as the previous API, but hard to come up with a better name. Other options are `setSpace` and `setWhiteSpace`.

### Other convenience API to consider
**Set M size spacing around and in between children**:
`setSpacing(true)`
- Not sure if needed, as it’s pretty easy to write `setSpacing(Space.M)` as well).

**Remove all spacing**:
`setSpacing(false)`
- Not sure if needed, as it’s pretty easy to write `setSpacing(Space.NONE)` as well).

**Comment by Legioth** [comment]
Controlling all the whitespace "slots" through one API is a quite neat idea.

Some random thoughts:
* Left and right can be tricky when it comes to RTL UIs
* Inside is a slightly challenging concept that might have different meanings for different types of "layouts". The two cases that come to mind are wrappers that only support a single child or something like a grid layout that could support different inside spacing in each direction. It could still be that it would be best to just keep things simple and use the same API consistently for all cases. You can always do fine grained tweaking through CSS if necessary.

**Comment by jouni** [comment]
[I added another suggestion](https://github.com/vaadin/vaadin-ordered-layout/issues/3#issuecomment-343119012) to the web component related issue (which I currently prefer for that part).

Here’s how it would work in Flow (this one doesn’t feel as good as the previous):

**Set internal, in between child components, spacing to M and padding to L**:
```java
layout.getElement().setAttribute("theme", Valo.Layout.GAP_M + " " + Valo.Spacing.PADDING_L);

// There will probably be a less verbose API for setting the theme variants, 
// but we haven’t designed that yet. Not sure how this feels:
layout.setTheme(Valo.Layout.GAP_M, Valo.Spacing.PADDING_L);
```

**Set padding to M**:
```java
// The problem here is that we expect the style scope, that this component/element is in, 
// having included the "valo-spacing" style module
component.getElement().setAttribute("theme", Valo.Spacing.PADDING_M);
```

**Set horizontal margin to XL**:
```java
component.getElement().setAttribute("theme", Valo.Spacing.MARGIN_HORIZONTAL_XL);
```

**Comment by pleku** [comment]
I think the API for the following example needs to be _more higher level_ or otherwise it makes to me very little value for even having the API since doesn't look to me to be that convenient to use.
```
layout.getElement().setAttribute("theme", Valo.Layout.GAP_M + " " + Valo.Spacing.PADDING_L);

// There will probably be a less verbose API for setting the theme variants, 
// but we haven’t designed that yet. Not sure how this feels:
layout.setTheme(Valo.Layout.GAP_M, Valo.Spacing.PADDING_L);
```

**Comment by pleku** [comment]
But, how do these styles combine together ? Should each call to the `theme` attribute add more variables there ?

How 'bout 
```java
layout.setGapBetweenComponents(Valo.Spacing.Padding_L);
// the above would internally use
layout.getElement().setAttribute("theme", Valo.Layout.GAP_M + " " + Valo.Spacing.PADDING_L);
```

For the other examples I'm not sure what the margin or padding are actually applied for, but just throwing this out there:
```java
layout.setSpacing(Valo.Spacing.Padding_M);
layout.setMargin(Valo.Spacing.Horizontal_XL);
```

**Comment by heruan** [comment]
I wouldn't tight code to theme elements (such `Valo.*`). Setting gaps is not a theme-specific choice, the amount of space is, therefore I'd want to change the theme and get the theme-driver amount of space where needed, without change my code.

**Comment by heruan** [comment]
I'm right now trying to port a Bootstrap app to Flow with Valo, so where I have:

```html
<div class="container">
  <div class="row">
    <div class="col">
      <h1>col1</h1>
    </div>
    <div class="col">
      <h1>col2</h1>
    </div>
  </div>
</div>
```

I know contents of the two `col`s are nicely spaced from both the viewport margin and each other. In Flow I'd do this:

```java
VerticalLayout container = new VerticalLayout();
HorizontalLayout row = new HorizontalLayout();
VerticalLayout col1 = new VerticalLayout(new H1("col1"));
VerticalLayout col2 = new VerticalLayout(new H1("col2"));
row.add(col1, col2);
container.add(row);
```

Right now the two `<h1>`s are not spaced from the viewport margin, nor from each other. A use case like this could be easier specializing the layouts, e.g.

```java
row.getElement().setAttribute("theme", "row-with-gaps");
col1.getElement().setAttribute("theme", "col-with-padding");
col2.getElement().setAttribute("theme", "col-with-padding");
```

So the theme knows how I'm using the layouts and can apply its own spacing styles.

**Comment by jouni** [comment]
> But, how do these styles combine together ? Should each call to the theme attribute add more variables there ?

My idea was that it would always override the attribute, but you could pass multiple values, separated with comma.

**About terminology**, so that we understand and use them consistently: 
- Spacing refers to all white space in general (contrary to FW7/8, where “spacing” means “gap” between children)
- Margin and padding refer directly to CSS margin and padding properties
- Gap refers to the feature provided by a layout that adds white space in between its children

> Setting gaps is not a theme-specific choice, the amount of space is

I agree in general. But we have heard requests that it would be helpful if you could control the amount of spacing from Java as well. But, this could be something for which we do not provide a convenience API.

**Comment by heruan** [comment]
> But we have heard requests that it would be helpful if you could control the amount of spacing from Java as well.

Of course, then Flow can provide a set of semantic theme-related constants in e.g. `Theme.*`, then themes can implement style for them:

```java
myLayout.getTheme().add(Theme.Layout.GAP_M); // treating "theme" attribute as list
```

**Comment by jouni** [comment]
> verticalLayout.getTheme().add(…)

🤦‍♂️ too obvious… that’s, of course, the way it should work. Just like the class attribute works. The original name for the `theme` attribute was actually `theme-class` 😊

---

I would still make the constants theme-specific (`Valo.Layout.GAP_M` vs . `Theme.Layout.GAP_M`) since the exact presets could be different. 

The `gap` part is probably a requirement for all themes, that all themes need to provide at least `GAP_NONE` to disable gaps (as they would be enabled by default).

Same for margin/padding, that all themes should probably have at least one constant for them, i.e. `layout.getTheme().add(MyTheme.Layout.MARGIN)` and `layout.getTheme().add(MyTheme.Layout.PADDING)`.

Would that be simple enough for a “Java guy”, without any other convenience API? Or should we still ad the following:

**Toggle on**
```java
layout.setMargin(true);
  → layout.getTheme().add("margin"); // …and remove any other margin values

layout.setPadding(true);
  → layout.getTheme().add("padding"); // …and remove any other padding values

layout.setGap(true);
  → Remove all gap values (they are enabled by default)
```

**Toggle off**
```java
layout.setMargin(false);
  → Remove all margin values

layout.setPadding(false);
  → Remove all padding values

layout.setGap(false);
  → layout.getTheme().add("gap-none"); // …and remove any other gap values
```

**Set granular values**
```java
layout.setMargin(Valo.Layout.Margin.L);
  → layout.getTheme().add("margin-l"); // …and remove any other margin values

layout.setPadding(Valo.Layout.Padding.S);
  → layout.getTheme().add("padding-s"); // …and remove any other padding values

layout.setGap(Valo.Layout.Gap.M);
  → layout.getTheme().add("gap-m"); // …and remove any other gap values
```

**Comment by tmattsso** [comment]
That API looks simple enough for me (a java developer).

**Comment by jouni** [comment]
@tmattsso, can you be very explicit, which is simple enough:

`layout.getTheme().add(MyTheme.Layout.MARGIN_M);`

or 

`layout.setMargin(true);`

**Comment by tmattsso** [comment]
The second one, definitely. Remember, we are trying to keep DX at a similar level to 8. Also, #FFS.

**Comment by heruan** [comment]
> I would still make the constants theme-specific (Valo.Layout.GAP_M vs . Theme.Layout.GAP_M) since the exact presets could be different.

For very specific styles Valo could have its `Valo.*` set of constants, but why not having a canonical preset of theme keys for common concepts like spacing, to which themes can conform to provide their own values? The specific web component may set its defaults then, if the theme does not provide a value for that key. Then for a basic app switching theme won't require mass refactoring.

**Comment by jouni** [comment]
@tmattsso, good, just wanted to make sure my assumption was correct.

@heruan, yeah. That’s pretty much how the FW7/8 works, having margin and spacing as core layout features.  Sounds okay to me. Coming full circle, I suppose 😄

**Comment by Legioth** [comment]
Support has been merged into the web component, but it has not yet been released. https://github.com/vaadin/vaadin-ordered-layout/pull/8

**Comment by pleku** [comment]
There are further issues for `vaadin-ordered-layout` so we should postpone this until everything is resolved and then fix it for good.

**Comment by pleku** [comment]
Skipping the spacing for now, will be added in a separate issue.

The added API for horizontal and vertical layouts in this:
```java
void setMargin(boolean margin);
void setPadding(boolean padding);
Theme getTheme();
```
`Theme` should have at least the `add` `remove` and `clear` methods. It would make sense to look at `ClassList` and have similar API as that since it basically does the same thing.

### Acceptance Criteria
There is a demo for using margin and padding for horizontal & vertical layouts.

**Comment by heruan** [comment]
I suppose `ThemeList` should be added to `flow-server`, am I right? Or does it exist already?

**Comment by Legioth** [comment]
@heruan `ThemeList` should not be specific to these components, but I'm also not sure it should be in `vaadin-server` for the same reason as the Valo WebJar dependency discussion from https://github.com/vaadin/flow/issues/3199.

**Comment by pleku** [comment]
Yes, it will be there in `flow-server`, since it has no ties to Valo (or any other theme). It is just a convenience method for modifying the `theme` attribute.

The proposal for spacing API considers the parts about the variants #34.

**Comment by Legioth** [comment]
The `theme` attribute means nothing special for an arbitrary HTML element. It's only defined for our own elements, or other custom component implementations that explicitly choose to follow our conventions.

For this reason, it's slightly weird to have it in `flow-server` which is in theory independent of the used component set. On the other hand, it doesn't directly hurt to have it there, compared to the WebJar dependency that I was referring to.

**Comment by heruan** [comment]
> The `theme` attribute means nothing special for an arbitrary HTML element. It's only defined for our own elements, or other custom component implementations that explicitly choose to follow our conventions.

I'm sure I've recently read in some Polymer member's blog post of the introduction of a `::theme` CSS selector, so maybe that attribute is about to be in the spec. I'll look for the post to reference it here!

**Comment by jouni** [comment]
@heruan, `::theme` is the proposed CSS pseudo-element for selecting parts inside deeply nested shadow roots, and it doesn’t introduce a `theme` HTML attribute. The `part` attribute is introduced by the same spec proposal, though, which we are already also using.

The `theme` attribute is just a convention I came up with and I’ve been wondering why no one has raised any objections to it so far. 

My reason for using that instead of the standard `class` attribute is to avoid potential naming conflicts with 3rd party CSS libraries or legacy codebases, where our elements might be used. For example, I expect some codebases to have `.error`, `.success` and `.primary` classes defined, which might mess up the styles for `vaadin-button`.

I also don’t want to namespace all of the style/theme variations for our elements, e.g. `<vaadin-button class="valo-primary">`. Though, that is an option.

If somehow feasible, I would rather use the standard `class` attribute than something invented by us.
