### ISSUE TITLE
Expecting same behavior of element counterparts

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-ordered-layout-flow#18]
Why these stylings are necessary in layout constructors?

```java
public VerticalLayout() {
    getStyle().set("flexDirection", "column").set("width", "100%");
    setDefaultHorizontalComponentAlignment(Alignment.START);
}
```
and
```java
public HorizontalLayout() {
    getStyle().set("display", "inline-flex").set("flexDirection", "row");
    setDefaultVerticalComponentAlignment(Alignment.BASELINE);
}
```

I would expect the Flow components to behave like the custom elements, without the need to set properties explicitly. Also, they are difficult to override using CSS, since they are set on the element itself. Even for the 100% width, I would expect to be set in `vaadin-vertical-layout` element style (via `:host` selector), not here.

**Comment by pleku** [comment]
These are the same defaults as in the Framework has had since 8.0, where they were _fixed_ to have them since we wanted to provide them as _sensible defaults_.

Should these be on the web component instead, or should we change them again, @jouni ?

You can change these from the Java API, doesn't need CSS for that.

**Comment by heruan** [comment]
Note that:

- there defaults are already on the web component style;
- latest releases of `vaadin-ordered-layout` introduces a inner `div` as a flex container, so these properties won't affect the children when updating the web component version, since the flex container is no more the component host element (see also https://github.com/vaadin/vaadin-ordered-layout/issues/14).

**Comment by pleku** [comment]
That means that the whole component should be updated to be based on the `alpha3` version of the `vaadin-ordered-layout` and there these defaults should be removed too.

I'll run the generator to add an updated element, after that your PR can be merged

**Comment by pleku** [comment]
Right, no need to update the generator since it is not used on purpose ... 

Just should be enough that you update the version (by overriding it) in the `pom.xml` for the webjars, to use `1.0.0-alpha3`.

**Comment by jouni** [comment]
We’re just about to set the `align-items` to `flex-start` in the web component as well, after which it should have the same defaults as the ones in the issue description.

**Comment by jouni** [comment]
I’m actually now trying to find confirmation that we should use `flex-start` as the default alignment.

> These are the same defaults as in the Framework has had since 8.0, where they were fixed to have them since we wanted to provide them as sensible defaults.

I think the only things we adjusted in FW8 regarding layouts was to set the margin and spacing to be on by default. The default alignments were not touched, and have been the same since the early days, I believe.

We did, however, make it easier to “expand/flex” components in FW8, so perhaps that’s one indicator that making ”stretch” the default would not be a terrible idea. There’s also probably some good reason the CSS spec has that as the default.

There’s always the option to make this easily configurable per layout. I don’t have any good sense which behavior would be more often needed, so I can only assume it’s 50/50.

**Comment by jouni** [comment]
Ping @Legioth and @tomivirkki, I guess we can keep the discussion here?

**Comment by jouni** [comment]
One common use case for a horizontal layout is placing a few fields and buttons side by side, and for that case, neither `flex-start` or `stretch` is the desired behavior. `flex-end` would be the correct.

![screen shot 2017-11-30 at 11 33 12](https://user-images.githubusercontent.com/66382/33423709-4cb9b414-d5c2-11e7-97d0-196ac01355e2.png)

**Comment by heruan** [comment]
> Just should be enough that you update the version […]

Mind that the wrapper element introduced in the latest version also makes `FlexLayout` methods like `setJustifyContentMode` useless, unless they are changed to target `#layout`. Since there are also issues about overflow due to negative margin compensation on that element, I guess it's better to wait a decision on https://github.com/vaadin/vaadin-ordered-layout/issues/14 first about how to update the Flow components.

**Comment by pleku** [comment]
### Acceptance Criteria
- We should fix the API to match the one that is in the web component and not introduce any extra
- `FlexLayout` can still live as its own component for now

**Comment by heruan** [comment]
Does #19 satisfy the criteria? I'm not sure what do you mean with "not introduce any extra". If you're referring to the `FlexElement` mixin interface, IMHO it fits in this refactoring as for the missing enum values which complete the API. I'm asking just to be sure on how to proceed 😃
