### ISSUE TITLE
Inconsistent default values in layout properties.

### ISSUE THREAD

**Issue by RapidClipse** [vaadin/vaadin-ordered-layout-flow#88]
VerticalLayout#getDefaultHorizontalComponentAlignment says in the JavaDoc that the default value is START (which according to the behaviour it is), but it returns AUTO.

Same in HorizontalLayout#getDefaultVerticalComponentAlignment. And also getDefaultVerticalComponentAlignment says default is STRETCH, and setDefaultVerticalComponentAlignment says it's START.

**Comment by denis-anisimov** [comment]
The description is confusing and doesn't confirm to the behavior at least in the `master` branch.

`getDefaultHorizontalComponentAlignment says in the JavaDoc that the default value is START`.
Yes.
`but it returns AUTO`. No. It returns `STRETCH` (see test below).
`Same in HorizontalLayout#getDefaultVerticalComponentAlignment`.
No.
`And also getDefaultVerticalComponentAlignment says default is STRETCH` .
Yes. And that's why the previous statement is not really correct.
`setDefaultVerticalComponentAlignment says it's START`.
Yes.

Here is the test which I use and it passes:
```
    @Test
    public void defaultAlignmentValues() {
        VerticalLayout verticalLayout = new VerticalLayout();
        Assert.assertEquals(Alignment.STRETCH,
                verticalLayout.getDefaultHorizontalComponentAlignment());

        HorizontalLayout horizontalLayout = new HorizontalLayout();
        Assert.assertEquals(Alignment.STRETCH,
                horizontalLayout.getDefaultVerticalComponentAlignment());

    }
```

It confirms the code which uses `STRETCH` as a default value.

So there is an issue but the behavior differs from the description.
So I would like to know the version of the component which you use and have AUTO for the default values.
